version: '3'
services:
  webserver:
    container_name: webserver_gb
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.224
      PHP_IDE_CONFIG: serverName=localhost
    ports:
      - 81:80
    volumes:
      - /yii2calendar.gb:/var/www
    links:
      - db
    depends_on:
      - db

  db:
    container_name: mysql_gb
    image: 'mysql:latest'
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqluser
    volumes:
      - /yii2calendar.gb/docker/database:/var/lib/mysql

  memcached:
    container_name: memcached_gb
    image: sameersbn/memcached:1.5.6
    ports:
      - 11212:11211
    restart: always